### ISSUE TITLE
Veto skips error checking

### ISSUE THREAD

**Issue by MarcusScott483** [MarcusScott483/Poonanji-s-Game-Selector#2]

**Comment by adamstol** [comment]
Is this issue already fixed?

**Comment by MarcusScott483** [comment]
@WTIOFlameburst It's not fixed, and ready for work. :)

**Comment by adamstol** [comment]
You can assign this to me!

When you mean "skips error checking" do you mean that it should only respond to 'y' or 'n'? or do you mean something else?

**Comment by MarcusScott483** [comment]
@WTIOFlameburst The problem is, if the user selects "veto", and then chooses to create a new list, the newly created list can be smaller than 2 games because it doesn't check the size of currentlist. Also, we made this just for fun in our group of friends and we're new to GitHub, how did you find the repo? We appreciate your interest. :))

**Comment by adamstol** [comment]
I'm also new to GitHub, I found this scrolling through the issues category looking to see if there were any issues I could help with. Also I see the issue now.

**Comment by adamstol** [comment]
I fixed the issue and added some corrections to your code for better readability. I also suggest you comment on your work although for a simple algorithm like this one it's not a big deal. I'm just having some troubles pushing the files back because its my first time, sorry.

**Comment by MarcusScott483** [comment]
@WTIOFlameburst I see, what part are you stuck on? Were you able to create a pull request?

**Comment by adamstol** [comment]
It should be good now I made a pull request, please take a look 😁
